### PR TITLE
Add just-posted image from xkcd.com

### PR DESCRIPTION
**Pull request by dtgriscom**
Randall just posted another image for xkcd 1446; I've added it to the img directory and to the list, and have noted that the event is no longer over.

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
Dupe of #19, I think, but I like the `index.html` change that’s missing there.

**Comment by dtgriscom** [comment]
Missed that one (I'm new at this).

It looks like there's a no-longer-enabled daemon to check for new images; you might want to fire it up again (although I don't know how).


Let me know if I can help otherwise,
Dan

Daniel T. Griscom, Suitable Systems
1 Centre Street, Suite 204, Wakefield, MA  01880-2400
(781) 665-0053  griscom@suitable.com  http://www.suitable.com/

**Comment by thomasrussellmurphy** [comment]
Which is preferred? I would be willing to include the comment on not-ending of the event in my PR.

**Comment by dtgriscom** [comment]
I'm fine with using either pull request. Just get it done; for all we know Randall's drawing new images as we speak!

Daniel T. Griscom, Suitable Systems
1 Centre Street, Suite 204, Wakefield, MA  01880-2400
(781) 665-0053  griscom@suitable.com  http://www.suitable.com/

**Comment by dtgriscom** [comment]
No reason to have this outstanding at this point.

**Pull request closed without merging**
